const FETCH_MOVIES = 'FETCH_MOVIES';
const FETCH_MOVIE_BY_ID = 'FETCH_MOVIE_BY_ID';
const FETCH_PAGES = 'FETCH_PAGES';
const FETCH_GENRES = 'FETCH_GENRES';

export {FETCH_MOVIES, FETCH_MOVIE_BY_ID, FETCH_PAGES, FETCH_GENRES}